### ISSUE TITLE
steps to get id and secrets

### ISSUE THREAD

**Issue by hirenchalodiya1** [Klemensas/chrome-extension-upload-action#2]
- can you add documentation, how to get those `client-id` and `client-secret` from Google APIs. specifically which services do we have to choose? for example, which options should I choose to get my credentials?
![image](https://user-images.githubusercontent.com/32496777/95000415-41380100-05de-11eb-9c96-035a2a1f82cf.png)

**Comment by VahidNaderi** [comment]
It's explained [here](https://medium.com/@hi.lucas.p/continuously-deploying-a-chrome-extension-e95eeb7cca81) how to get those parameters.
